// Tests for the Gemini ledger reader (sessions-spike WU v5-4, design §4.3 /
// §9).
//
// The ledger fixture `fixtures/external-tools/external-tools.jsonl` is NOT
// hand-authored — it was generated by actually invoking metaswarm's real
// `emit_json` / `log_session` bash functions from
// `skills/external-tools/adapters/_common.sh`; see
// `fixtures/external-tools/README.md` for the exact, re-runnable provenance.
//
// `discoverGeminiRuns` reads metaswarm's append-only external-tools ledger
// (`~/.claude/sessions/external-tools.jsonl`) and yields one `DelegationRun`
// per `tool === "gemini"` entry. `tool === "codex"` entries are ignored
// (Codex is read directly by the v5-3 rollout reader). The §9 hardening — an
// allow-list Zod parse that structurally drops the secret-bearing `command`
// and `raw_log`, a per-line cap, and a total-file-size cap — is exercised
// here against the real fixture and over `mkdtemp` temp files.

import {
  mkdtempSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DelegationRun } from '@metaswarm-dashboard/types/cost';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import * as sessions from '../../index.js';
import {
  type LedgerReaderFsHooks,
  discoverGeminiRuns,
} from '../ledger-reader.js';

const FIXTURE = join(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'external-tools',
  'external-tools.jsonl',
);

describe('discoverGeminiRuns — against the real-emit_json fixture (§4.3)', () => {
  it('yields exactly the two gemini entries (the codex entry is ignored)', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    // Fixture: gemini, codex, gemini(failed), gemini(schema_version 2),
    // malformed, blank. Only the two schema_version-1 gemini runs survive.
    expect(runs).toHaveLength(2);
    for (const run of runs) {
      expect(run.vendor).toBe('google');
    }
  });

  it('every yielded run is `vendor: "google"` — never openai/anthropic', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    expect(runs.map((r) => r.vendor)).toEqual(['google', 'google']);
  });

  it('costs a priced gemini run from cost.input_tokens / cost.output_tokens', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    const priced = runs.find((r) => r.model === 'gemini-3-pro');
    expect(priced).toBeDefined();
    // gemini-3-pro: input 2, output 12 (per 1M). The other TokenUsage fields
    // are 0 — the ledger only carries input/output token counts.
    expect(priced!.usage).toEqual({
      inputTokens: 48200,
      outputTokens: 6100,
      cacheReadTokens: 0,
      cacheCreation5mTokens: 0,
      cacheCreation1hTokens: 0,
      reasoningTokens: 0,
    });
    // 48200*2 + 6100*12 = 96400 + 73200 = 169600 / 1e6 = 0.1696
    expect(priced!.costUsd).toBeCloseTo(0.1696, 9);
  });

  it('maps `at` from the ledger `timestamp`', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    const priced = runs.find((r) => r.model === 'gemini-3-pro');
    expect(priced!.at).toBe('2026-05-18T22:13:40.000Z');
  });

  it('sets projectName: null — the ledger carries no cwd (unattributed)', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    for (const run of runs) {
      expect(run.projectName).toBeNull();
    }
  });

  it('still costs a FAILED gemini run (non-zero exit / error_type set)', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    // The failed run uses gemini-2.5-pro with 1200/0 tokens.
    const failed = runs.find((r) => r.model === 'gemini-2.5-pro');
    expect(failed).toBeDefined();
    expect(failed!.usage.inputTokens).toBe(1200);
    expect(failed!.usage.outputTokens).toBe(0);
    // gemini-2.5-pro: input 1.25 → 1200*1.25 = 1500 / 1e6 = 0.0015
    expect(failed!.costUsd).toBeCloseTo(0.0015, 9);
  });

  it('every yielded run round-trips the DelegationRun schema', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    for (const run of runs) {
      expect(() => DelegationRun.parse(run)).not.toThrow();
    }
  });

  it('returns runs in a deterministic order (sorted by at, then model)', () => {
    const a = discoverGeminiRuns(FIXTURE);
    const b = discoverGeminiRuns(FIXTURE);
    expect(a).toEqual(b);
  });
});

describe('discoverGeminiRuns — allow-list parse drops secret fields (§9)', () => {
  it('`command` is provably absent from every parsed run object', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    for (const run of runs) {
      expect('command' in run).toBe(false);
      // A deep stringify must not surface the secret-bearing command text.
      expect(JSON.stringify(run)).not.toContain('SECRET_TOKEN');
      expect(JSON.stringify(run)).not.toContain('API_KEY');
    }
  });

  it('`raw_log` is provably absent from every parsed run object', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    for (const run of runs) {
      expect('raw_log' in run).toBe(false);
      expect('rawLog' in run).toBe(false);
    }
  });

  it('the run object has exactly the DelegationRun keys — nothing else', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    for (const run of runs) {
      expect(Object.keys(run).sort()).toEqual([
        'at',
        'costUsd',
        'model',
        'projectName',
        'usage',
        'vendor',
      ]);
    }
  });
});

describe('discoverGeminiRuns — schema_version handling (§4.3)', () => {
  it('skips an entry whose schema_version is unrecognized', () => {
    const runs = discoverGeminiRuns(FIXTURE);
    // The schema_version "2" gemini line carries git_sha ffffffff… — it must
    // not appear; the two surviving runs are both schema_version 1.
    expect(runs).toHaveLength(2);
    expect(runs.some((r) => r.model === 'gemini-3-pro' && r.usage.inputTokens === 100)).toBe(false);
  });
});

describe('discoverGeminiRuns — empty state (§4.3)', () => {
  it('an absent ledger file → empty array, no throw', () => {
    expect(discoverGeminiRuns('/no/such/external-tools.jsonl')).toEqual([]);
  });

  it('an empty ledger file → empty array', () => {
    const dir = mkdtempSync(join(tmpdir(), 'ledger-empty-'));
    try {
      const file = join(dir, 'external-tools.jsonl');
      writeFileSync(file, '');
      expect(discoverGeminiRuns(file)).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('a ledger with only a codex entry → empty array (gemini-only reader)', () => {
    const dir = mkdtempSync(join(tmpdir(), 'ledger-codex-only-'));
    try {
      const file = join(dir, 'external-tools.jsonl');
      writeFileSync(
        file,
        '{"schema_version":"1","tool":"codex","model":"gpt-5.3-codex","cost":{"input_tokens":1,"output_tokens":1},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}\n',
      );
      expect(discoverGeminiRuns(file)).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('discoverGeminiRuns — malformed / robustness (§9)', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'ledger-robust-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function ledger(...lines: string[]): string {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(file, lines.join('\n'));
    return file;
  }

  const GEMINI_LINE =
    '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","cost":{"input_tokens":10,"output_tokens":5},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}';

  it('skips a malformed JSON line and still reads the rest', () => {
    const runs = discoverGeminiRuns(ledger('{ this is not json', GEMINI_LINE));
    expect(runs).toHaveLength(1);
    expect(runs[0]!.model).toBe('gemini-3-pro');
  });

  it('skips a blank line', () => {
    const runs = discoverGeminiRuns(ledger('', GEMINI_LINE, '   '));
    expect(runs).toHaveLength(1);
  });

  it('skips a >1 MiB line without decoding it', () => {
    const huge = `{"junk":"${'x'.repeat(1024 * 1024 + 10)}"}`;
    const runs = discoverGeminiRuns(ledger(huge, GEMINI_LINE));
    expect(runs).toHaveLength(1);
    expect(runs[0]!.model).toBe('gemini-3-pro');
  });

  it('tolerates a trailing newline / no trailing newline alike', () => {
    expect(discoverGeminiRuns(ledger(GEMINI_LINE))).toHaveLength(1);
    expect(discoverGeminiRuns(ledger(GEMINI_LINE, ''))).toHaveLength(1);
  });

  it('tolerates CRLF line endings', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(file, `${GEMINI_LINE}\r\n${GEMINI_LINE}\r\n`);
    expect(discoverGeminiRuns(file)).toHaveLength(2);
  });

  it('strips a UTF-8 BOM from the first line only', () => {
    const file = join(dir, 'external-tools.jsonl');
    // A leading BOM (﻿) on line 1 — `log_session` never writes one, but
    // an editor / transfer might prepend one. It must not break the parse.
    writeFileSync(file, `﻿${GEMINI_LINE}\n${GEMINI_LINE}\n`);
    expect(discoverGeminiRuns(file)).toHaveLength(2);
  });

  it('skips a non-UTF-8 line', () => {
    const file = join(dir, 'external-tools.jsonl');
    // An invalid UTF-8 byte sequence on its own line, then a valid record.
    writeFileSync(
      file,
      Buffer.concat([
        Buffer.from([0xff, 0xfe, 0x0a]),
        Buffer.from(`${GEMINI_LINE}\n`, 'utf-8'),
      ]),
    );
    expect(discoverGeminiRuns(file)).toHaveLength(1);
  });

  it('skips an entry missing the cost object', () => {
    const noCost =
      '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}';
    expect(discoverGeminiRuns(ledger(noCost, GEMINI_LINE))).toHaveLength(1);
  });

  it('coerces a negative / non-finite token count to 0', () => {
    const weird =
      '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","cost":{"input_tokens":-50,"output_tokens":5},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}';
    const runs = discoverGeminiRuns(ledger(weird));
    expect(runs).toHaveLength(1);
    expect(runs[0]!.usage.inputTokens).toBe(0);
    expect(runs[0]!.usage.outputTokens).toBe(5);
  });

  it('a non-conforming timestamp falls back to the epoch', () => {
    const badTs =
      '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","cost":{"input_tokens":10,"output_tokens":5},"git_sha":"abc","timestamp":"not-a-date"}';
    const runs = discoverGeminiRuns(ledger(badTs));
    expect(runs).toHaveLength(1);
    expect(runs[0]!.at).toBe(new Date(0).toISOString());
  });
});

describe('discoverGeminiRuns — deterministic ordering', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'ledger-sort-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function geminiAt(timestamp: string, model = 'gemini-3-pro'): string {
    return `{"schema_version":"1","tool":"gemini","model":"${model}","cost":{"input_tokens":1,"output_tokens":1},"git_sha":"abc","timestamp":"${timestamp}"}`;
  }

  it('sorts runs by `at` ascending, regardless of file order', () => {
    const file = join(dir, 'external-tools.jsonl');
    // Written newest-first; the result must come back oldest-first.
    writeFileSync(
      file,
      [
        geminiAt('2026-05-18T23:00:00Z'),
        geminiAt('2026-05-18T21:00:00Z'),
        geminiAt('2026-05-18T22:00:00Z'),
      ].join('\n'),
    );
    const runs = discoverGeminiRuns(file);
    expect(runs.map((r) => r.at)).toEqual([
      '2026-05-18T21:00:00.000Z',
      '2026-05-18T22:00:00.000Z',
      '2026-05-18T23:00:00.000Z',
    ]);
  });

  it('breaks an equal-`at` tie by model name', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(
      file,
      [
        geminiAt('2026-05-18T22:00:00Z', 'gemini-3-pro'),
        geminiAt('2026-05-18T22:00:00Z', 'gemini-2.5-pro'),
      ].join('\n'),
    );
    const runs = discoverGeminiRuns(file);
    expect(runs.map((r) => r.model)).toEqual(['gemini-2.5-pro', 'gemini-3-pro']);
  });
});

describe('discoverGeminiRuns — unpriced model → costUsd null (§5.3)', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'ledger-unpriced-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('an unpriced gemini model yields costUsd: null, never 0', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(
      file,
      '{"schema_version":"1","tool":"gemini","model":"gemini-99-ultra","cost":{"input_tokens":10,"output_tokens":5},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}\n',
    );
    const runs = discoverGeminiRuns(file);
    expect(runs).toHaveLength(1);
    expect(runs[0]!.costUsd).toBeNull();
    // The usage is still recorded — only the price is unknown.
    expect(runs[0]!.usage.inputTokens).toBe(10);
  });
});

describe('discoverGeminiRuns — total-file-size cap (§9)', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'ledger-bigfile-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  const GEMINI_LINE =
    '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","cost":{"input_tokens":10,"output_tokens":5},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}\n';

  it('refuses a ledger larger than the total-file-size cap → empty array', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(file, GEMINI_LINE);
    // A tiny cap makes the (small) real file exceed it.
    expect(discoverGeminiRuns(file, undefined, { maxFileBytes: 10 })).toEqual([]);
  });

  it('reads a ledger at or below the cap normally', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(file, GEMINI_LINE);
    const size = statSync(file).size;
    expect(
      discoverGeminiRuns(file, undefined, { maxFileBytes: size }),
    ).toHaveLength(1);
  });

  it('the default cap admits a normal ledger', () => {
    const file = join(dir, 'external-tools.jsonl');
    writeFileSync(file, GEMINI_LINE);
    expect(discoverGeminiRuns(file)).toHaveLength(1);
  });
});

describe('discoverGeminiRuns — injectable fs hooks', () => {
  it('uses injected hooks instead of node:fs', () => {
    const ledgerBody =
      '{"schema_version":"1","tool":"gemini","model":"gemini-3-pro","cost":{"input_tokens":7,"output_tokens":3},"git_sha":"abc","timestamp":"2026-05-18T22:13:40Z"}\n';
    const fakeFs: LedgerReaderFsHooks = {
      statSync: () => ({ size: Buffer.byteLength(ledgerBody) }),
      readFileSync: () => Buffer.from(ledgerBody, 'utf-8'),
    };
    const runs = discoverGeminiRuns('/virtual/ledger.jsonl', fakeFs);
    expect(runs).toHaveLength(1);
    expect(runs[0]!.usage.inputTokens).toBe(7);
  });

  it('a statSync that throws (absent file) → empty array, no throw', () => {
    const fakeFs: LedgerReaderFsHooks = {
      statSync: () => {
        throw new Error('ENOENT');
      },
      readFileSync: () => Buffer.from(''),
    };
    expect(discoverGeminiRuns('/virtual/missing.jsonl', fakeFs)).toEqual([]);
  });

  it('a readFileSync that throws → empty array, no throw', () => {
    const fakeFs: LedgerReaderFsHooks = {
      statSync: () => ({ size: 100 }),
      readFileSync: () => {
        throw new Error('EACCES');
      },
    };
    expect(discoverGeminiRuns('/virtual/unreadable.jsonl', fakeFs)).toEqual([]);
  });
});

describe('@metaswarm-dashboard/sessions public surface — v5-4', () => {
  it('re-exports discoverGeminiRuns from the package barrel', () => {
    expect(typeof sessions.discoverGeminiRuns).toBe('function');
  });
});
